Danger DOOM in the hizzy!
Widdy widdy widdy widdy widdy widdy widdy we
We need food
What are you doin there?
I'm rappin
Yeah... no, no I see that - what for?
Money - if you got it umm
I wanna get some steady bitches and hoes
And some candy for my nose
Some diamond stones, to roll with my chrome and..
Hey, genius. You even know what that means?
Uh-uh - what does it mean?
Where's the keyboards, and the tambourine, and the guitar
And you know, I mean - the stuff that like, white people like
We had a piano
Somethin bad-ass, like uhh, I don't know
Like uhh, REO Speedwagon or somethin
Hell yeah!
Aiyyo, I know this dude right
Carl, he wore tight blue sweats but wasn't glued too tight
All he had upstairs was a crude light
You think that's weird? He lived next door to a food fight
Howdy Danger, much obliged for the beat God
Even though you still eat lard, by the Meatwad
Mesquite charred, speakin of which or who
Voice all squeaky like they tuned it up a pitch or two
A chunk of burned up witch's brew, get your crew
See if they can't get past the stench of the stew
It stank like a septic tank full of pig poo
He mostly only turned into a frank or a igloo
Switch your view to the brother with the fried dreads
Not to be confused with the incense selling thai heads
His name rhymes with Mike Hawk
You could call him livewire, eye sockets, Frylock
Able to shoot electricity through his eyeballs
And blast all through your single sided brick and drywall
More interesting than professional wrestling
When he's online, you can find him on Instant Pestering
What's up with your boy? He's not a soft or hot drink
Whoever don't like it could suck his straw, it's hot pink
On some junk like Gucci on a classy ho
Might splash you in the face with nuclear pistachio
Make a fast break, or that'll be the last mistake
That ass'll make is what you get for messin with Master Shake
Look out, don't block the screen son, lunge across
Tryin to watch Adult Swim, "Aqua Teen Hunger Force!"
Rock a cult hymn, sock your mean younger boss
Psht - Adult Swim, "Aqua Teen Hunger Force!"
He often wondered, should he get the logo tatted to his woody?
He could be "#1 in the hood, G!"
Easily
(*BEEP!!*}
Shake callin, he heh
You know I wa-ahhhhhhaaaaeehh
I'd just got off the phone with somebody else and uh
That wasn't about you
That was about me being upset about something else
I shouldn't have called you but I did, cause I just
I like you so much, I'm REALLY looking forward to us working together
And just, as of now that I'm calm
And after I've apologized profusely - probably too much
I am available, call me doggie - woof!
{*phone hangs up*}